{
 "title": "Torrust Live Demo Tracker (stats)",
 "description": "Using stats endpoint:\n\nhttps://tracker.example.com/api/v1/stats?token=MyAccessToken&format=prometheus",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Completed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "completed{job=\"tracker_stats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Torrents",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "torrents{job=\"tracker_stats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Seeders",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "seeders{job=\"tracker_stats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Leechers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "leechers{job=\"tracker_stats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UDP4 Connections (per sec)",
   "type": "timeseries",
   "description": "Request per second in 15 minutes",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "rate(udp4_connections_handled{job=\"tracker_stats\"}[15m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UDP4 Announces (per sec)",
   "type": "timeseries",
   "description": "Request per second in 15 minutes",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 5 },
   "targets": [
    {
     "expr": "rate(udp4_announces_handled[15m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UDP4 Scrapes (per sec)",
   "type": "timeseries",
   "description": "Request per second in 15 minutes",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "rate(udp4_scrapes_handled[15m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UDP4 Errors (per sec)",
   "type": "timeseries",
   "description": "Request per second in 15 minutes",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 5 },
   "targets": [
    { "expr": "rate(udp4_errors_handled[15m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "UDP Average Connect Time",
   "type": "timeseries",
   "description": "UDP Average Connect Processing Time",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "udp_avg_connect_processing_time_ns{job=\"tracker_stats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UDP Average Announce Time",
   "type": "timeseries",
   "description": "UDP Average Announce Processing Time",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "udp_avg_announce_processing_time_ns{job=\"tracker_stats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UDP Average Scrape Time",
   "type": "timeseries",
   "description": "UDP Average Scrape Processing Time",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "udp_avg_scrape_processing_time_ns{job=\"tracker_stats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UDP banned requests (per second)",
   "type": "timeseries",
   "description": "UDP banned requests (per second)",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 14 },
   "targets": [
    {
     "expr": "rate(udp_requests_banned{job=\"tracker_stats\"}[15m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UDP4 requests and responses (per second)",
   "type": "timeseries",
   "description": "UDP 4 requests and responses",
   "gridPos": { "h": 13, "w": 18, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "rate(udp4_requests{job=\"tracker_stats\"}[15m])",
     "legendFormat": "__auto"
    },
    { "expr": "rate(udp4_responses[15m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "UDP Banned IPs",
   "type": "timeseries",
   "description": "UDP Banned IPs",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 19 },
   "targets": [
    {
     "expr": "udp_banned_ips_total{job=\"tracker_stats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UDP aborted requests (per second)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 25 },
   "targets": [
    {
     "expr": "rate(udp_requests_aborted{job=\"tracker_stats\"}[15m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}