#!/bin/bash
# ============================================================================
# Torrust Backup Maintenance Script
# ============================================================================
#
# This file was generated by the Torrust Tracker Deployer.
#
# DOCUMENTATION:
#   Repository:    https://github.com/torrust/torrust-tracker-deployer
#   Script:        templates/backup/maintenance-backup.sh
#   Crontab:       templates/backup/maintenance-backup.cron.tera
#   API Docs:      https://docs.rs/torrust-tracker-deployer/latest/
#
# DESCRIPTION:
#   Maintenance script for backup orchestration during scheduled maintenance windows.
#   Implements graceful shutdown pattern: stop tracker → backup → restart tracker.
#   This ensures data consistency by preventing new writes during backup operations.
#   Designed to run via cron with proper logging and error handling.
#
# For configuration options and valid values, see the API documentation link above.
# ============================================================================

set -euo pipefail

# Logging configuration
LOG_FILE="/var/log/tracker-backup.log"
LOG_DIR="$(dirname "$LOG_FILE")"

# Create log directory if it doesn't exist
mkdir -p "$LOG_DIR"

# Logging functions
log_info() {
    local timestamp
    timestamp=$(date '+%Y-%m-%d %H:%M:%S')
    echo "[$timestamp] INFO: $*" | tee -a "$LOG_FILE"
}

log_error() {
    local timestamp
    timestamp=$(date '+%Y-%m-%d %H:%M:%S')
    echo "[$timestamp] ERROR: $*" | tee -a "$LOG_FILE" >&2
}

log_section() {
    local timestamp
    timestamp=$(date '+%Y-%m-%d %H:%M:%S')
    echo "" | tee -a "$LOG_FILE"
    echo "[$timestamp] ========================================" | tee -a "$LOG_FILE"
    echo "[$timestamp] $*" | tee -a "$LOG_FILE"
    echo "[$timestamp] ========================================" | tee -a "$LOG_FILE"
}

# Trap errors and ensure tracker is restarted even if backup fails
cleanup_on_exit() {
    local exit_code=$?
    
    if [ $exit_code -ne 0 ]; then
        log_error "Backup process failed with exit code $exit_code"
        log_info "Attempting to restart tracker..."
    fi
    
    # Always try to restart the tracker
    if ! start_tracker; then
        log_error "Failed to restart tracker - manual intervention required"
        exit 1
    fi
    
    log_section "Backup maintenance completed (exit code: $exit_code)"
    exit $exit_code
}

trap cleanup_on_exit EXIT

# Helper function to check if we're in the application directory
check_directory() {
    if [ ! -f "docker-compose.yml" ]; then
        log_error "docker-compose.yml not found - must run from /opt/torrust directory"
        return 1
    fi
    return 0
}

# Stop the tracker container gracefully
stop_tracker() {
    log_info "Stopping tracker container..."
    
    if docker compose stop tracker >/dev/null 2>&1; then
        log_info "Tracker stopped successfully"
        return 0
    else
        log_error "Failed to stop tracker"
        return 1
    fi
}

# Start the tracker container
start_tracker() {
    log_info "Starting tracker container..."
    
    if docker compose up -d tracker >/dev/null 2>&1; then
        log_info "Tracker started successfully"
        return 0
    else
        log_error "Failed to start tracker"
        return 1
    fi
}

# Run the backup container
run_backup() {
    log_info "Running backup container..."
    
    if docker compose run --rm backup >/dev/null 2>&1; then
        log_info "Backup completed successfully"
        return 0
    else
        log_error "Backup container exited with error"
        return 1
    fi
}

# Main execution
main() {
    log_section "Starting backup maintenance"
    
    # Verify we're in the right directory
    if ! check_directory; then
        return 1
    fi
    
    # Execute the maintenance steps
    if ! stop_tracker; then
        return 1
    fi
    
    if ! run_backup; then
        # Don't return here - cleanup_on_exit will handle restart
        return 1
    fi
    
    log_info "Backup maintenance completed successfully"
    return 0
}

# Run main function
main
